### ISSUE TITLE
calling update-deps.sh fails

### ISSUE THREAD

**Issue by yuvalif** [knative/eventing-contrib#1571] opened 2020-09-15 09:23 UTC
get the following error:
```
warning: ignoring symlink /home/ylifshit/go/src/knative.dev/eventing-contrib/test/test_images/kafka_performance/kodata/refs
go: knative.dev/test-infra@v0.0.0-20200910231400-cfba2288403d requires
        k8s.io/test-infra@v0.0.0-20200803112140-d8aa4e063646 requires
        github.com/GoogleCloudPlatform/testgrid@v0.0.13 requires
        vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml on 10.35.255.14:53: no such host
```

**Comment by MIBc** [comment] 2020-09-15 14:36
It seems like a dns problem.

**Comment by yuvalif** [comment] 2020-09-15 17:08
> It seems like a dns problem.

do you mean it is a temporary problem?

**Comment by MIBc** [comment] 2020-09-16 02:31
Check you dns config. `10.35.255.14` is not a public dns server.

**Comment by yuvalif** [comment] 2020-09-16 08:05
I've set the IP statically (changing DNS didn't seem to help), but now I get a cert issue:
```
vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": x509: certificate has expired or is not yet valid: current time 2020-09-16T10:49:51+03:00 is after 2020-01-03T23:59:59Z
```

**Comment by yuvalif** [comment] 2020-09-16 08:17
I've set the dns address to a public one, but didn't seem to help:
```
 vbom.ml/util@v0.0.0-20180919145318-efcd4e0f9787: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml on 1.1.1.1:53: no such host
```

**Comment by tom24d** [comment] 2020-09-16 09:31
@yuvalif Which `Go` version are you using?
I cannot reproduce this with go 1.15.2 even if I drop all related go mod cache.
Note that vbom.ml/util has been moved to github.com/fvbommel/util(See the issue 7 in that repo).

**Comment by yuvalif** [comment] 2020-09-16 09:49
go version go1.14.6 linux/amd64

**Comment by pierDipi** [comment] 2020-09-16 10:03
I've just tried on Fedora 32 with the same Go version and it's working.

Can you share the output of the command `go env`?

**Comment by yuvalif** [comment] 2020-09-16 10:17
```
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ylifshit/.cache/go-build"
GOENV="/home/ylifshit/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ylifshit/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ylifshit/go/src/knative.dev/eventing-contrib/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build446643634=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by pierDipi** [comment] 2020-09-16 10:33
It seems ok.

Are you on the default branch?

/priority awaiting-more-evidence

**Comment by yuvalif** [comment] 2020-09-16 12:03
> It seems ok.
> 
> Are you on the default branch?
> 
yes, on "master"

> /priority awaiting-more-evidence

**Comment by lberk** [comment] 2020-09-16 15:47
fwliw, I've hit this as well on the `test-infra` repo

**Comment by lberk** [comment] 2020-09-17 20:28
For those coming here via search, considering this is a dns issue (instead of a eventing-contrib issue) and I've verified others users are hitting this well, I've manually worked around the issue by adding a `replace` line in go.mod to avoid using the vanity url, ie:
`vbom.ml/util => github.com/fvbommel/util v0.0.2`

Closing this issue out for now

**Closed by lberk** 2020-09-17 20:28 UTC
Labels: kind/bug
