### ISSUE TITLE
inline k8s corev1 Container over ContainerSourceSpec

### ISSUE THREAD

**Issue by rootfs** [knative/eventing-contrib#55] opened 2018-11-01 14:54 UTC
## Expected Behavior
[ContainerSourceSpec](https://github.com/knative/eventing-sources/blob/master/pkg/apis/sources/v1alpha1/containersource_types.go#L37) has some but not all k8s corev1 Container. If k8s corev1 Container is inlined here, we then don't need to hardcode the pull policy [here](https://github.com/knative/eventing-sources/blob/master/pkg/controller/containersource/resources/deployment.go#L72) and will make is easier for sources that base on ContainerSource.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Additional Info

@n3wscott @grantr

**Comment by n3wscott** [comment] 2018-11-01 15:58
Perhaps container source should bump out and have a the container template?

**Comment by rootfs** [comment] 2018-11-01 16:02
if that is not a big inconvenience, please get a pod template

**Comment by n3wscott** [comment] 2018-11-01 16:19
I think it is a good idea. @evankanderson and @grantr were looking at this a bit too

**Comment by sebgoa** [comment] 2018-12-28 21:16
+1 to this.

We need to be able to use a full Pod spec in the Container source manifest.

Being able to use secrets as env variables is one good use-case.

**Comment by sebgoa** [comment] 2019-01-02 20:07
@tzununbekov let's discuss this one, I think you could help here

**Comment by vaikas-google** [comment] 2019-01-16 18:50
Makes sense to add the pod template. however, you should be able to use env secrets today as is. not disputing the need for pods.

**Comment by sebgoa** [comment] 2019-01-28 08:33
confirmed env configured via secrets do work. However volumes mounts don't. 

If you create a container source for Google cloud for instance, you need to set GOOGLE_APPLICATION_CREDENTIALS to a file path where you mount the service account secret.

Therefore today we cannot write a Container source for Google services.

**Comment by vaikas-google** [comment] 2019-06-10 06:44
I'm closing this because this has been fixed by using the podtemplatespec. Re-open if there's something else that's needed.
https://github.com/knative/eventing/pull/1321

**Closed by vaikas-google** 2019-06-10 06:44 UTC
